### ISSUE TITLE
[Bug]: `interface_workaround` not a valid option

### ISSUE THREAD

**Issue by AlejandroRivera** [3DCoded/DynamicMacros#11]
### What happened?

I've  updating all my dependencies 
![image](https://github.com/user-attachments/assets/3836bdc9-7a7c-40be-bfa2-6c8d44a7503a)

and i've added the `interface_workaround: true` to `[dynamicmacros]` as shown below:
![image](https://github.com/user-attachments/assets/ff30a1ca-7f98-4e7d-a05c-5978d4c1f29a)

but when I restart, i see this error:
![image](https://github.com/user-attachments/assets/30c543b5-181d-4601-b7eb-77ae1b8d6f24)

I've also confirmed the updated code contains the new field in `dynamicmacros.py`:
```
fly@voron0:~/DynamicMacros$ grep -C2 workaround dynamicmacros.py
        self.config_parser = MacroConfigParser(self.printer)

        if config.getboolean('interface_workaround', False):
            self.interface_workaround()

        self._update_macros()

    def interface_workaround(self):
        full_cfg = StringIO()
        for fname in self.fnames:
--
        self.config_parser = MacroConfigParser(self.printer)

        if config.getboolean('interface_workaround', False):
            self.interface_workaround()

        self._update_macros()
```

### Klippy Log

```
DynamicMacros: Reading section gcode_macro PRINT_START_NOZZLE_CLEANUP
DynamicMacros: Reading section gcode_macro WIPE_NOZZLE
DynamicMacros: Reading section gcode_macro WIPE_NOZZLE_WHEN_RESUMING
DynamicMacros: Reading section gcode_macro POOP
Extruder max_extrude_ratio=2.078758
Config error
Traceback (most recent call last):
  File "/home/fly/klipper/klippy/klippy.py", line 130, in _connect
    self._read_config()
  File "/home/fly/klipper/klippy/klippy.py", line 127, in _read_config
    pconfig.check_unused_options(config)
  File "/home/fly/klipper/klippy/configfile.py", line 493, in check_unused_options
    self.validate.check_unused(config.fileconfig)
  File "/home/fly/klipper/klippy/configfile.py", line 442, in check_unused
    raise error("Option '%s' is not valid in section '%s'"
configparser.Error: Option 'interface_workaround' is not valid in section 'dynamicmacros'
```

**Comment by 3DCoded** [comment]
Did you run the install script?

```
cd ~/DynamicMacros
sh install.sh
```

The `dynamicmacros.py` may contain the new code, but you still need to run the install script to update it inside Klipper.

**Comment by AlejandroRivera** [comment]
oh, yes, you're right. I thought the install script would be executed automatically!

Things seem to be working fine now. thanks!
